### ISSUE TITLE
Go TODO

### ISSUE THREAD

**Issue by loganmc10** [simple64/simple64-netplay-server#16]
- [x] Lag should not report 255 when the count is bigger than the lead count (should probably be 0)
- [x] Test/finish desync
- [x] Make a function that checks if one uint32 is bigger than another
- [x] Test settings sync
- [x] Does the TCP server close when a player leaves? It shouldn't, needs to close at the same time as udp
